name: card_selector_example
description: A demo app to illustrate a wallet.
version: 1.0.0+1
author: Victor Bonnet<victor.bonnet@gmail.com>
homepage: https://github.com/victorbonnet/flutter_card_selector

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  card_selector: ^0.0.1
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - in.json
    - visa.png
    - mastercard.png
    - dots.png
    - layers.png
    - circles.png

  fonts:
    - family: rms
      fonts:
        - asset: fonts/RemachineScript.ttf

