name: CardSelector
description: Widget selector for Flutter using stack.
version: 0.0.1
author: Victor Bonnet<victor.bonnet@gmail.com>
homepage: https://github.com/victorbonnet/flutter_card_selector

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
